default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: eric
  password: i2o0o0

development:
  <<: *default
  database: projectname_development

test:
  <<: *default
  database: projectname_test

production:
  <<: *default
  database: projectname_production
